strings = input()
print(strings[2])
print(strings[-2])
print(strings[:5])
print(strings[:-2:1])
print(strings[0::2])
print(strings[1::2])
print(strings[::-1])
print(strings[-1::-2])
print(len(strings))
